// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS4NRucpF0s3qGmGneIXkEKqowMqvKAxs',
    appId: '1:45487484453:android:2de50259905bb4697399cc',
    messagingSenderId: '45487484453',
    projectId: 'notes-app-macos',
    storageBucket: 'notes-app-macos.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-7QXP3qw8RF_Fvu9mYcv-tSheUdzVciM',
    appId: '1:45487484453:ios:5aef7bc692cd18f97399cc',
    messagingSenderId: '45487484453',
    projectId: 'notes-app-macos',
    storageBucket: 'notes-app-macos.firebasestorage.app',
    androidClientId: '45487484453-dj4kvtsglpr3v36p4ed13t8m8i12ueg9.apps.googleusercontent.com',
    iosClientId: '45487484453-0o600hg1uoa7qkfkh64a2ql5c5bmt57r.apps.googleusercontent.com',
    iosBundleId: 'com.mynotes.app',
  );

}