default_platform(:android)

platform :android do

  desc "Upload AAB to Google Play internal testing track"
  lane :internal do
    upload_to_play_store(
      track:               "internal",
      aab:                 "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_apk:     true,
      skip_upload_images:  true,
      skip_upload_screenshots: true,
    )
  end

  desc "Promote internal build to production"
  lane :promote_to_production do
    upload_to_play_store(
      track:        "internal",
      track_promote_to: "production",
      skip_upload_aab: true,
    )
  end

end
